project:
  type: website
  output-dir: docs

website:
  title: "Jocelyn Magner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: travels.qmd
        text: Travels
      - href: resume.qmd
        text: Resume
format:
  html:
    theme: 
      - flatly
      - styles.scss
    mainfont: IBM Plex Sans
    toc: true
    page-layout: full